#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec \
    s6-notifyoncheck -d -n 300 -w 1000 \
        cd / s6-setuidgid abc /app/kavita/bin/Kavita
# app config is based on the folder the app is run from
